####################################
# YoloV5 model weight path
weight: "weights/best.pt"
# Input image size
input_size: 640
# Number of classes
class_num:  1
# Class names

class_name: [ 'Box_Obstacle' ]

# Threshold settings
threshold:
  iou: 0.45
  confidence: 0.1
# Computing device
# - cpu
# - 0 <- Use GPU
device: '0'
